spring:
  application:
    name: service-auth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.211.55.12:3306/spring-cloud-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 5000
  context-path: /uaa
security:
  oauth2:
    resource:
      filter-order: 3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/